port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
global-client-fingerprint: chrome
dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fallback:
  - https://1.0.0.1/dns-query
  - tls://dns.google
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
proxies:
- name: hysteria | 🇺🇸美国4
  type: hysteria
  server: 167.160.90.252
  port: 48089
  auth-str: dongtaiwang.com
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
  skip-cert-verify: true
- name: vmess | 🇨🇦加拿大1
  type: vmess
  server: dongtaiwang2.com
  port: 443
  cipher: auto
  uuid: f5c180eb-fbce-49ac-9029-482eca9385c0
  alterId: 0
  tls: true
  skip-cert-verify: true
  servername: ''
  network: ws
  ws-opts:
    path: /gzogws
    headers:
      host: xray1.freeh1.xyz
- name: vless | 🇨🇦加拿大1
  type: vless
  server: dongtaiwang2.com
  port: 443
  uuid: ffb15cd2-0521-49de-b8aa-fb15d58c8075
  tls: true
  servername: v2ray3.freegradely.xyz
  network: ws
  ws-opts:
    path: /bqbows
    headers:
      host: v2ray3.freegradely.xyz
  client-fingerprint: chrome
- name: hysteria | 🇹🇼台湾3
  type: hysteria
  server: 111.243.97.209
  port: 22334
  auth-str: dongtaiwang.com
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
  skip-cert-verify: true
- name: hysteria | 🇹🇼台湾3
  type: hysteria
  server: www4.dtku49.xyz
  port: 22334
  auth-str: dongtaiwang.com
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
  skip-cert-verify: true
- name: hysteria | 🇹🇼台湾3
  type: hysteria
  server: www.dtku50.xyz
  port: 56252
  sni: www.amazon.cn
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  auth_str: dongtaiwang.com
  up: 2
  down: 10
- name: hysteria | 🇺🇸美国4
  type: hysteria
  server: 64.110.25.10
  port: 44556
  auth-str: dongtaiwang.com
  alpn:
  - h3
  protocol: udp
  up: 11 Mbps
  down: 55 Mbps
  skip-cert-verify: true
- name: hysteria | 🇬🇧英国1
  type: hysteria
  server: 62.204.54.81
  port: 44550
  sni: bing.com
  skip-cert-verify: true
  alpn:
  - h3
  protocol: udp
  auth_str: dongtaiwang.com
  up: 5
  down: 10
- name: hysteria | 🇺🇸美国4
  type: hysteria
  server: 167.160.91.115
  port: 41189
  ports: 41189
  auth_str: bWAwIqINo7XDm1fUlXQGBifVIXoYs1ylgVKqWFKzK1XyDKuwNF
  up: 80
  down: 100
  fast-open: true
  protocol: udp
  sni: www.amazon.cn
  skip-cert-verify: true
  alpn:
  - h3
- name: hysteria | 🇺🇸美国5
  type: hysteria
  server: 173.234.25.52
  port: 30072
  ports: 30072
  auth_str: dongtaiwang.com
  up: 80
  down: 100
  fast-open: true
  protocol: udp
  sni: bing.com
  skip-cert-verify: true
  alpn:
  - h3
- name: hysteria | 🇨🇦加拿大1
  type: hysteria
  server: 108.181.22.239
  port: 39967
  ports: 39967
  auth_str: dongtaiwang.com
  up: 80
  down: 100
  fast-open: true
  protocol: udp
  sni: bing.com
  skip-cert-verify: true
  alpn:
  - h3
- name: hysteria | 🇫🇷法国1
  type: hysteria
  server: 51.158.54.46
  port: 11926
  ports: 11926
  auth_str: Trz2alKwzCImRAXI3nXfpo1ylpHfqOL8s1vageWKoyjjvWeMVs
  up: 80
  down: 100
  fast-open: true
  protocol: udp
  sni: youku.com
  skip-cert-verify: true
  alpn:
  - h3
proxy-groups:
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - DIRECT
- name: 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - hysteria | 🇺🇸美国4
  - vmess | 🇨🇦加拿大1
  - vless | 🇨🇦加拿大1
  - hysteria | 🇹🇼台湾3
  - hysteria | 🇹🇼台湾3
  - hysteria | 🇹🇼台湾3
  - hysteria | 🇺🇸美国4
  - hysteria | 🇬🇧英国1
  - hysteria | 🇺🇸美国4
  - hysteria | 🇺🇸美国5
  - hysteria | 🇨🇦加拿大1
  - hysteria | 🇫🇷法国1
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
